### ISSUE TITLE
Error at installation: plugins is not defined

### ISSUE THREAD

**Issue by SubstanceDesign** [postcss/sugarss#30]
I do not know, what must be in 'plugins' variable. I am beginner and don't found this answer in manual https://github.com/postcss/sugarss

May be you tell me?

**gulpfile.js:**

var sugarss = require('sugarss');
var postcss = require('gulp-postcss');
var rename  = require('gulp-rename');
var autoprefixer = require('autoprefixer');
var cssnano = require('cssnano');

38  gulp.task('style', function () {
39     return gulp.src('build/templates/*.sss')
40         .pipe(postcss(plugins, { parser: sugarss }))
41         .pipe(rename({ extname: '.css' }))
42         .pipe(gulp.dest('app/templates/'));
43  });

**Error:**

ReferenceError: plugins is not defined
    at Gulp.<anonymous> (/Users/user/Documents/Project/gulpfile.js:40:23)
    at module.exports (/Users/user/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/user/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/user/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/Users/user/node_modules/orchestrator/index.js:134:8)
    at /usr/local/lib/node_modules/gulp-cli/lib/versioned/^3.7.0/index.js:46:20
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Function.Module.runMain (module.js:577:11)
    at startup (node.js:160:18)

**Comment by ai** [comment]
https://github.com/postcss/sugarss/issues/29

**Comment by SubstanceDesign** [comment]
I do not know, what must be in 'plugins' variable. I am beginner and don't found this answer in manual https://github.com/postcss/sugarss

May be you tell me?
